#!/usr/bin/env ruby

require 'clap'
require 'security_report/cli'

cli = CLI.new

files = Clap.run ARGV,
  "-h" => cli.method(:help),
  "--help" => cli.method(:help),
  "--format" => cli.method(:format=),
  "--update" => cli.method(:update)

cli.run(files)
